services:
  base: &base
    image: chatwoot/chatwoot:v4.6.0-ce
    env_file: .env 
    volumes:
      - storage_data:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '0.0.0.0:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env 
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis_data:/data
    ports:
      - '127.0.0.1:6379:6379'
  ai-agent:
    build:
      context: /home/amalsboui/Projects/AI/ai-support-agent
    restart: always
    env_file: /home/amalsboui/Projects/AI/ai-support-agent/.env
    volumes:
      - ai_agent_data:/data
    ports:
      - "8000:8000"   
    depends_on:
    - rails
    - postgres
    - redis
    networks:
      default:
        aliases:
          - ai-agent.local

volumes:
  storage_data:
  postgres_data:
  redis_data:
  ai_agent_data:

